[global]
frame_color = "#81c8be"
separator_color= frame
highlight = "#81c8be"

[urgency_low]
background = "#303446"
foreground = "#c6d0f5"

[urgency_normal]
background = "#303446"
foreground = "#c6d0f5"

[urgency_critical]
background = "#303446"
foreground = "#c6d0f5"
frame_color = "#ef9f76"
