[global]
frame_color = "#74c7ec"
separator_color= frame
highlight = "#74c7ec"

[urgency_low]
background = "#1e1e2e"
foreground = "#cdd6f4"

[urgency_normal]
background = "#1e1e2e"
foreground = "#cdd6f4"

[urgency_critical]
background = "#1e1e2e"
foreground = "#cdd6f4"
frame_color = "#fab387"
