[global]
frame_color = "#94e2d5"
separator_color= frame
highlight = "#94e2d5"

[urgency_low]
background = "#1e1e2e"
foreground = "#cdd6f4"

[urgency_normal]
background = "#1e1e2e"
foreground = "#cdd6f4"

[urgency_critical]
background = "#1e1e2e"
foreground = "#cdd6f4"
frame_color = "#fab387"
